titleAlwaysFitsScreen = true
scoreboardMode = "OVERLAY"
scoreboardFadeSpeed = 0
scoreboardHideMinAlpha = 0
titleMarginLeft = 8
titleMarginRight = 8
preferredTitleScale = 4.0
preferredSubtitleScale = 2.0
